In [105]:
import pandas as pd
import numpy as np

In [106]:
df = pd.read_csv('../data/realestate_data_sample.csv')
df

,title,address,price,details.dien-tich-dat,details.phong-ngu,details.nha-tam,details.phap-ly,details.ngay-dang,details.ma-bds,content,...,district_lat,district_lon,average_price,num_of_ward,used_area,land_area,reg_area,diff,area_times,num_of_floor
0,bán nhà vi bằng hiệp thành quận 12 giá 950 triệu,"bùi văn ngữ, phường hiệp thành, quận 12, tphcm",63.333333,"15 m2 (3,5x5)",2.0,1.0,Hợp đồng mua bán,22/04/2023,22125937,Bán 2 Căn Nhà Vi bằng. Bùi Văn Ngữ Hiệp Thành...,...,10.861557,106.578293,43.90,11,30.0,15.0,17.5,2.5,2.000000,1.0
1,"bán nhà đường lạc long quân, lô góc, phong các...","lạc long quân, phường 10, quận tân bình, tphcm",153.333333,"30 m2 (4,2x7)",3.0,3.0,Sổ đỏ,19/10/2022,21837379,"MÔ TẢ:+ Vị trí: Giao cáo tuyến đường Âu Cơ, Hồ...",...,10.803629,106.612072,146.90,15,30.0,30.0,29.4,0.6,1.000000,2.0
2,"nhà bán quận 4 , đoàn văn bơ, phường 16","đoàn văn bơ, phường 16, quận 4, tphcm",116.666667,15 m2 (4x4),1.0,2.0,Sổ hồng,03/03/2023,22040491,"Mua bán , giấy tờ sang tên nhanh chóng Tiện íc...",...,10.760791,106.683567,164.40,15,30.0,15.0,16.0,1.0,2.000000,NaN
3,bán nhà đường tam châu phường tam bình thủ đức...,"tam châu, phường tam bình, quận thủ đức (tp. t...",51.666667,30 m2 (3x10),2.0,1.0,Giấy tờ hợp lệ,27/01/2023,21961802,-kết cấu 2 tầng đúc kiên cố 2 phòng ngủ.-nhà c...,...,10.820455,106.625025,49.50,12,30.0,30.0,30.0,0.0,1.000000,2.0
4,nhà mới đẹp quận 8 - 3 tầng đúc full nội thất ...,"lê thành phương, phường 15, quận 8, tphcm",110.000000,30 m2 (3x10),4.0,4.0,Sổ đỏ,22/03/2023,21872303,"Lê Thành Phương, Q.8 - Diện tích : 30m2, 3...",...,10.723041,106.562972,84.50,18,30.0,30.0,30.0,0.0,1.000000,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47744,chdv nguyễn cửu vân p17 bình thạnh 9x18 6 lầu ...,"nguyễn cửu vân, phường 17, quận bình thạnh, tphcm",296.296296,162 m2 (9x18),22.0,22.0,Sổ hồng,12/08/2023,22195974,CHDV hẻm 46 Nguyễn Cửu Vân p17 Bình Thạnh Dt 9...,...,10.812136,106.717669,149.18,20,900.0,162.0,162.0,0.0,5.555556,6.0
47745,đất nền 3 mặt hẻm 805m2 thạnh lộc 27 q12,"thạnh lộc 27, phường thạnh lộc, quận 12, tphcm",36.024845,"805 m2 (28,2x28,5)",NaN,NaN,Sổ đỏ,19/09/2022,21764892,BÁN ĐẤT NỀN 3 MẶT HẺM NGAY CHUNG CƯ FIRST HOME...,...,10.861557,106.578293,43.90,11,912.0,805.0,803.7,1.3,1.132919,NaN
47746,"thu nhập 1,4 tỷ.1năm, hầm,trệt 5 lầu có thang ...","phạm văn hai, phường 2, quận tân bình, tphcm",192.592593,"135 m2 (4,5x30)",6.0,7.0,Sổ đỏ,14/08/2023,22252088,DÀNH CHO KHÁCH ĐẦU TƯ HAY MUA GIỮ TIỀN THU NHẬ...,...,10.803629,106.612072,146.90,15,944.0,135.0,135.0,0.0,6.992593,5.0
47747,bán nhà vườn thị trấn hóc môn giá rẻ 960m2- ch...,"quốc lộ 22, thị trấn hóc môn, huyện hóc môn, t...",14.062500,"960 m2 (34,5x28)",4.0,4.0,Sổ đỏ,29/12/2022,21804780,Dành cho NHÀ ĐẦU TƯ SÀNH SỎI- Chỉ 14tr/m...,...,10.877999,106.429011,26.50,12,960.0,960.0,966.0,6.0,1.000000,NaN
47748,"cần bán tòa nhà building 7 lầu, 2 mặt tiền lê ...","lê văn sỹ, phường 14, quận 3, tphcm",478.571429,140 m2 (7x20),NaN,NaN,Sổ hồng,07/10/2022,21833964,Bán nhanh tòa nhà building 2 mặt tiền Lê Văn S...,...,10.779290,106.660524,290.60,14,980.0,140.0,140.0,0.0,7.000000,7.0

In [107]:
selected_cols = ['price', 'details.dien-tich-su-dung', 'details.phong-ngu', 'details.nha-tam', 'district']

In [108]:
df = df[selected_cols]

In [109]:
def extract_used_area(area):
    try:
        area = area.replace("m2", "")
        area = area.replace(",", ".")

        area = area.strip()
        try:
            return float(area)
        except:
            return np.nan
    except:
        return np.nan
df['used_area'] = df['details.dien-tich-su-dung'].apply(extract_used_area)

/tmp/ipykernel_1297535/3823880444.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['used_area'] = df['details.dien-tich-su-dung'].apply(extract_used_area)

In [110]:
df = df.dropna()

In [111]:
district = list(df['district'].unique())
district_dict = dict(zip(district, range(len(district))))
district_dict

{'quận 12': 0,
 'tân bình': 1,
 'quận 4': 2,
 'thủ đức': 3,
 'quận 8': 4,
 'quận 9': 5,
 'gò vấp': 6,
 'quận 5': 7,
 'quận 10': 8,
 'phú nhuận': 9,
 'quận 3': 10,
 'tân phú': 11,
 'bình thạnh': 12,
 'bình tân': 13,
 'quận 1': 14,
 'quận 7': 15,
 'quận 11': 16,
 'quận 6': 17,
 'quận 2': 18,
 'hóc môn': 19,
 'củ chi': 20,
 'bình chánh': 21,
 'nhà bè': 22,
 'cần giờ': 23}

In [112]:
df['district'] = df['district'].map(district_dict)
df['district'].value_counts()

1     5022
12    4783
6     4259
11    3365
13    2987
9     2422
3     2367
8     2285
0     2249
15    1782
5     1742
10    1672
4     1315
14    1137
17    1021
7      896
16     885
18     716
2      623
19     545
21     365
22     337
20      55
23       1
Name: district, dtype: int64

In [113]:
df = df[(df['district'] != 23) & (df['district'] != 20)]

In [114]:
df = df.reset_index(drop = True)

In [115]:
df = df.rename(columns = {
    'details.phong-ngu': 'num_of_bedroom',
    'details.nha-tam': 'num_of_bathroom',
})
df = df[['num_of_bedroom', 'num_of_bathroom', 'used_area', 'district', 'price']]

In [116]:
df.to_parquet('../data/processed_realestate_data_sample.parquet', index = False)

In [117]:
df

       num_of_bedroom  num_of_bathroom  used_area  district       price
0                 2.0              1.0       30.0         0   63.333333
1                 3.0              3.0       30.0         1  153.333333
2                 1.0              2.0       30.0         2  116.666667
3                 2.0              1.0       30.0         3   51.666667
4                 4.0              4.0       30.0         4  110.000000
...               ...              ...        ...       ...         ...
42770            23.0             25.0      900.0        14  441.176471
42771            23.0             23.0      900.0        12  168.181818
42772            22.0             22.0      900.0        12  296.296296
42773             6.0              7.0      944.0         1  192.592593
42774             4.0              4.0      960.0        19   14.062500

[42775 rows x 5 columns]

In [118]:
df['target'] = df['price'] * 1000 / df['used_area']

In [119]:
feat_set1 = ['num_of_bedroom', 'district']
feat_set2 = ['num_of_bathroom', 'district']
feat_set3 = ['num_of_bathroom', 'district', 'num_of_bedroom']
feat_set4 = ['num_of_bathroom', 'district', 'num_of_bedroom', 'used_area']


data_df1 = df[feat_set1]
data_df2 = df[feat_set2]
data_df3 = df[feat_set3]
data_df4 = df[feat_set4]
target_df = pd.DataFrame(data=df.target, columns=["target"])

In [120]:
timestamps = pd.date_range(
    end=pd.Timestamp.now(),
    periods=len(df),
    freq='D').to_frame(name="event_timestamp", index=False)

In [121]:
data_df1 = pd.concat(objs=[data_df1, timestamps], axis=1)
data_df2 = pd.concat(objs=[data_df2, timestamps], axis=1)
data_df3 = pd.concat(objs=[data_df3, timestamps], axis=1)
data_df4 = pd.concat(objs=[data_df4, timestamps], axis=1)
target_df = pd.concat(objs=[target_df, timestamps], axis=1)

In [122]:
realestate_ids = pd.DataFrame(data=list(range(len(df))), columns=["realestate_id"])

data_df1 = pd.concat(objs=[data_df1, realestate_ids], axis=1)
data_df2 = pd.concat(objs=[data_df2, realestate_ids], axis=1)
data_df3 = pd.concat(objs=[data_df3, realestate_ids], axis=1)
data_df4 = pd.concat(objs=[data_df4, realestate_ids], axis=1)
target_df = pd.concat(objs=[target_df, realestate_ids], axis=1)

In [123]:
data_df1.to_parquet(path='../data/data_df1.parquet')
data_df2.to_parquet(path='../data/data_df2.parquet')
data_df3.to_parquet(path='../data/data_df3.parquet')
data_df4.to_parquet(path='../data/data_df4.parquet')
target_df.to_parquet(path='../data/target_df.parquet')