In [15]:
import pandas as pd
import numpy as np

In [16]:
df = pd.read_csv('../../data/process_v1/process_data_7_hcm.csv')

In [17]:
selected_cols = [c for c in df.columns.tolist() if c not in ['target', 'time']]

In [18]:
timestamps = df['time'].tolist()
timestamps = pd.Series([pd.Timestamp(item) for item in timestamps])
timestamps = timestamps.to_frame(name="event_timestamp")

In [19]:
df = pd.concat(objs=[df, timestamps], axis=1)

In [20]:
df = df.sort_values(by = ['event_timestamp'])
df

,nearest_5_district,nearest_8_street,nearest_2_ward,nearest_4_district,nearest_1_district,typeOfRealEstate,houseDirection,nearest_5_street,nearest_7_street,street,...,distance_hn_DuongNguyenHuequan1TPHCM,nearest_4_lat,num_of_atm_in_2000m_radius,num_of_place_of_worship_in_2000m_radius,num_of_restaurant_in_1000m_radius,numberOfBathRooms,distance_hn_DuongNamKyKhoiNghia,time,target,event_timestamp
24794,11,1730,13,11,11,3,0,857,756,253,...,7.771465,10.790462,106,98,97,4.478184,7.835349,2023-04-01T00:00:00,450.000000,2023-04-01
37176,10,2986,547,10,10,3,0,4053,3429,493,...,8.572820,10.786360,35,72,15,4.478184,8.578963,2023-04-03T00:00:00,176.000000,2023-04-03
6905,11,100,518,11,11,3,0,495,100,2252,...,6.899570,10.766617,129,109,303,4.478184,6.688504,2023-05-18T00:00:00,406.250000,2023-05-18
6412,10,3640,438,14,14,0,1,3062,1479,1551,...,8.488024,10.803249,58,48,13,2.000000,8.519420,2023-07-13T00:00:00,69.863014,2023-07-13
24436,18,1998,28,18,18,1,4,208,2642,219,...,8.799135,10.799805,7,9,9,3.000000,8.820474,2023-07-14T00:00:00,185.000000,2023-07-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2697,1,357,116,1,1,1,0,3299,506,153,...,8.680754,10.736959,9,2,3,2.000000,8.654018,2024-02-16T00:00:00,96.250000,2024-02-16
22001,20,963,30,14,20,3,0,91,311,30,...,8.298848,10.805246,57,55,15,5.000000,8.345146,2024-02-16T00:00:00,123.595506,2024-02-16
21481,13,2268,399,13,13,1,7,2372,1469,2733,...,9.503459,10.886026,3,1,0,1.000000,9.516926,2024-02-16T00:00:00,51.875000,2024-02-16
10914,10,599,140,30,10,3,0,3708,3451,1047,...,8.989615,10.805946,17,12,3,4.478184,8.998477,2024-02-16T00:00:00,257.352941,2024-02-16
7477,100,100,140,100,30,1,1,100,100,761,...,9.110137,10.791475,12,7,1,4.478184,9.117437,2024-02-16T00:00:00,100.000000,2024-02-16

In [21]:
full_feat_set = selected_cols

data_df = df[full_feat_set + ['event_timestamp']]
target_df = df[['target'] + ['event_timestamp']]

In [22]:
realestate_ids = pd.DataFrame(data=list(range(len(data_df))), columns=["realestate_id"])

data_df = pd.concat(objs=[data_df, realestate_ids], axis=1)
target_df = pd.concat(objs=[target_df, realestate_ids], axis=1)

In [23]:
data_df.to_parquet(path='../../data/data_df_hcm.parquet')
target_df.to_parquet(path='../../data/target_df_hcm.parquet')

In [24]:
pd.read_parquet('/home/long/long/datn-feast/data/realestate_dataset_full_version.parquet').columns.tolist()

['target',
 'event_timestamp',
 'realestate_id',
 'nearest_5_district',
 'nearest_8_street',
 'nearest_2_ward',
 'nearest_4_district',
 'nearest_1_district',
 'typeOfRealEstate',
 'houseDirection',
 'nearest_5_street',
 'nearest_7_street',
 'street',
 'nearest_0_street',
 'nearest_4_street',
 'district',
 'nearest_6_ward',
 'nearest_8_district',
 'certificateOfLandUseRight',
 'nearest_1_ward',
 'nearest_8_ward',
 'nearest_3_district',
 'accessibility',
 'is_street_house',
 'nearest_0_ward',
 'nearest_6_street',
 'nearest_7_district',
 'nearest_2_district',
 'nearest_3_ward',
 'nearest_2_street',
 'nearest_7_ward',
 'ward',
 'nearest_6_district',
 'nearest_4_ward',
 'nearest_0_district',
 'nearest_3_street',
 'nearest_1_street',
 'nearest_5_ward',
 'distance_hn_Tran_Hung_Dao',
 'distance_hn_Diamond_Plaza_Shopping_Center',
 'num_of_police_in_2000m_radius',
 'num_of_place_of_worship_in_1000m_radius',
 'distance_hn_Cong_vien_nuoc_Cu_Chi',
 'num_of_parking_entrance_in_1000m_radius',
 'nearest_5_lon',
 'num_of_bank_in_2000m_radius',
 'landSize_ratio_with_administrative_genre',
 'distance_hn_Nguyen_Van_Linh',
 'num_of_atm_in_1000m_radius',
 'nearest_8_lon',
 'num_of_marketplace_in_2000m_radius',
 'num_of_cafe_in_2000m_radius',
 'landSize',
 'num_of_cafe_in_1000m_radius',
 'distance_nearest_4',
 'distance_hn_Ton_That_Thuyet',
 'distance_hn_Aeon_Mall_Shopping_Center_Tan_Phu',
 'num_of_university_in_2000m_radius',
 'num_of_marketplace_in_1000m_radius',
 'nearest_7_lat',
 'num_of_parking_in_500m_radius',
 'district_lat',
 'num_of_school_in_500m_radius',
 'numberOfFloors',
 'num_of_hospital_in_500m_radius',
 'nearest_6_lat',
 'distance_hn_Cong_vien_Gia_Dinh',
 'distance_hn_Cong_truong_Lam_Son',
 'distance_hn_Nguyen_Thi_Thap',
 'nearest_3_lat',
 'num_of_fast_food_in_500m_radius',
 'landSize_ratio',
 'acreage',
 'distance_nearest_1',
 'distance_hn_Hung_Vuong',
 'num_of_bank_in_1000m_radius',
 'distance_hn_Hau_Giang',
 'nearest_1_lon',
 'facade',
 'distance_hn_Cong_vien_cau_Anh_Sao_–_Ho_Ban_Nguyet',
 'distance_nearest_0',
 'distance_hn_Duong_Mac_Thi_Buoi',
 'num_of_parking_entrance_in_2000m_radius',
 'distance_hn_Cong_vien_ca_Koi_Rin_Rin_Park',
 'num_of_kindergarten_in_2000m_radius',
 'num_of_school_in_1000m_radius',
 'nearest_6_lon',
 'distance_hn_Ben_Van_Don',
 'distance_nearest_3',
 'distance_hn_Cong_vien_23-9',
 'w',
 'distance_hn_Kinh_Duong_Vuong',
 'h',
 'num_of_fast_food_in_1000m_radius',
 'num_of_university_in_1000m_radius',
 'nearest_2_lat',
 'distance_nearest_8',
 'num_of_townhall_-_community_centre_in_1000m_radius',
 'distance_nearest_5',
 'nearest_5_lat',
 'distance_hn_Duong_Le_Loi,_quan_1,_TPHCM',
 'num_of_restaurant_in_2000m_radius',
 'distance_hn_Cong_vien_Tao_Dan',
 'nearest_1_lat',
 'num_of_fuel_in_1000m_radius',
 'num_of_restaurant_in_500m_radius',
 'nearest_8_lat',
 'distance_hn_Doan_Van_Bo',
 'distance_hn_Duong_Nguyen_Hue,_quan_1,_TPHCM',
 'num_of_atm_in_500m_radius',
 'distance_hn_Crescent_Mall',
 'distance_hn_Duong_Le_Anh_Xuan,_quan_1',
 'distance_hn_TTTM_Saigon_Centre_(Takashimaya)',
 'num_of_kindergarten_in_500m_radius',
 'distance_hn_Nguyen_Thi_Minh_Khai',
 'num_of_cafe_in_500m_radius',
 'distance_hn_Cong_vien_khu_do_thi_Sala',
 'num_of_parking_in_2000m_radius',
 'distance_hn_Cong_vien_Tho_Trang',
 'num_of_fuel_in_500m_radius',
 'num_of_fast_food_in_2000m_radius',
 'distance_hn_Cong_vien_tren_may_tai_Taka_Shimaya',
 'distance_hn_Saigon_Garden',
 'distance_hn_Duong_Hai_Ba_Trung',
 'numberOfBedRooms',
 'distance_hn_Nguyen_Tri_Phuong',
 'distance_hn_Duong_Le_Duan',
 'distance_hn_SC_VivoCity_Shopping_Center',
 'nearest_0_lon',
 'num_of_parking_in_1000m_radius',
 'distance_hn_Duong_Nguyen_Tat_Thanh',
 'distance_nearest_2',
 'administrative_genre',
 'lon',
 'distance_nearest_6',
 'distance_hn_Thao_Cam_Vien',
 'distance_hn_Duong_Mai_Chi_Tho',
 'distance_hn_Duong_Nam_Ky_Khoi_Nghia',
 'density',
 'distance_hn_Cong_vien_Vinhomes_Central_Park',
 'distance_hn_Ba_Huyen_Thanh_Quan',
 'num_of_townhall_-_community_centre_in_500m_radius',
 'num_of_police_in_500m_radius',
 'nearest_4_lon',
 'distance_hn_Dao_Tri',
 'num_of_marketplace_in_500m_radius',
 'nearest_3_lon',
 'num_of_school_in_2000m_radius',
 'frontWidth',
 'distance_hn_Cong_vien_nuoc_Dam_Sen',
 'distance_hn_Cong_vien_Le_Van_Tam',
 'nearest_2_lon',
 'num_of_bank_in_500m_radius',
 'num_of_fuel_in_2000m_radius',
 'distance_district',
 'num_of_place_of_worship_in_500m_radius',
 'district_lon',
 'num_of_hospital_in_2000m_radius',
 'nearest_7_lon',
 'distance_hn_Cong_vien_30-4',
 'distance_hn_Le_Van_Sy',
 'distance_nearest_7',
 'population',
 'distance_hn_Duong_Vo_Chi_Cong',
 'num_of_police_in_1000m_radius',
 'num_of_ward',
 'num_of_kindergarten_in_1000m_radius',
 'lat',
 'distance_hn_Nguyen_Van_Luong',
 'nearest_0_lat',
 'acreage_ratio_with_meanLandSize',
 'num_of_university_in_500m_radius',
 'num_of_parking_entrance_in_500m_radius',
 'num_of_hospital_in_1000m_radius',
 'distance_hn_Cong_vien_Hoang_Van_Thu',
 'distance_hn_Duong_Dong_Khoi,_quan_1,_TPHCM',
 'distance_hn_Duong_Nguyen_Thi_Dinh',
 'distance_hn_Vincom_Dong_Khoi',
 'nearest_4_lat',
 'distance_hn_Le_Hong_Phong',
 'num_of_atm_in_2000m_radius',
 'num_of_place_of_worship_in_2000m_radius',
 'num_of_restaurant_in_1000m_radius',
 'num_of_townhall_-_community_centre_in_2000m_radius',
 'numberOfBathRooms',
 'distance_hn_Cong_vien_phep_thuat_Harry_Potter']