In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../../data/process_v1/process_data_8_hcm.csv')

In [3]:
selected_cols = [c for c in df.columns.tolist() if c not in ['target', 'time']]

In [4]:
timestamps = df['time'].tolist()
timestamps = pd.Series([pd.Timestamp(item) for item in timestamps])
timestamps = timestamps.to_frame(name="event_timestamp")

In [5]:
df = pd.concat(objs=[df, timestamps], axis=1)

In [6]:
df = df.sort_values(by = ['event_timestamp'])
df

,nearest_0_ward,nearest_8_ward,certificateOfLandUseRight,nearest_4_district,nearest_7_district,nearest_3_district,nearest_1_district,nearest_6_street,nearest_5_district,nearest_2_ward,...,num_of_marketplace_in_500m_radius,distance_hn_LeHongPhong,time,target,gmm_2_component_num_of_restaurant_in_2000m_radius,gmm_2_component_num_of_restaurant_in_1000m_radius,gmm_3_component_num_of_bank_in_2000m_radius,gmm_2_component_num_of_marketplace_in_2000m_radius,gmm_2_component_num_of_cafe_in_1000m_radius,event_timestamp
24760,13,13,0,11,11,11,11,991,11,13,...,1,8.283059,2023-04-01T00:00:00,450.000000,1,1,0,1,1,2023-04-01
37121,137,137,1,10,10,10,10,3100,10,547,...,1,8.140734,2023-04-03T00:00:00,176.000000,0,0,0,1,0,2023-04-03
6893,518,100,0,11,100,11,11,454,11,518,...,4,7.975209,2023-05-18T00:00:00,406.250000,1,1,2,0,1,2023-05-18
6401,438,38,1,14,10,10,14,1990,10,438,...,0,8.608067,2023-07-13T00:00:00,69.863014,0,0,0,1,0,2023-07-13
24402,28,172,1,18,0,18,18,3156,18,28,...,0,9.239047,2023-07-14T00:00:00,185.000000,0,0,1,1,0,2023-07-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30850,140,140,1,30,30,30,30,1534,30,140,...,0,8.980335,2024-02-16T00:00:00,142.000000,0,0,1,1,0,2024-02-16
5150,364,364,1,30,30,30,30,1095,30,364,...,1,8.564434,2024-02-16T00:00:00,89.421158,0,0,0,1,0,2024-02-16
41330,108,100,1,11,100,11,11,100,11,488,...,0,7.641707,2024-02-16T00:00:00,93.750000,1,1,0,0,1,2024-02-16
11161,391,391,1,42,42,42,42,3350,42,391,...,-1,9.398480,2024-02-16T00:00:00,83.333333,0,0,1,1,0,2024-02-16
20237,215,215,0,10,10,10,10,3805,10,215,...,0,8.635133,2024-02-16T00:00:00,291.044776,0,0,1,1,0,2024-02-16

In [7]:
full_feat_set = selected_cols

data_df = df[full_feat_set + ['event_timestamp']]
target_df = df[['target'] + ['event_timestamp']]

In [8]:
realestate_ids = pd.DataFrame(data=list(range(len(data_df))), columns=["realestate_id"])

data_df = pd.concat(objs=[data_df, realestate_ids], axis=1)
target_df = pd.concat(objs=[target_df, realestate_ids], axis=1)

In [9]:
data_df.to_parquet(path='../../data/data_df_hcm_v2.parquet')
target_df.to_parquet(path='../../data/target_df_hcm_v2.parquet')